version: '3.8'

services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/sss
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      DJANGO_SECRET_KEY: 'django-insecure-utj&iqqt!e+3(n$fg$)9$l)(y0h132g)s!6%+3iz@&1so-b86n'
      DATABASE_URL: sqlite:///sss/db.sqlite3  # Path within the container

volumes:
  postgres_data:
